In [10]:
import numpy as np
import pandas as pd
import math
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from skimage import io
from skimage.transform import resize
import warnings
warnings.filterwarnings('ignore')

In [33]:
# read data from sample and R
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
new_train = pd.read_csv("new_train.csv")
new_test = pd.read_csv("new_test.csv")
train_x = train.iloc[:, 2:786]
train_y = train.iloc[:,1]
new_train_x = new_train.iloc[:,1:]
new_test_x = new_test.iloc[:,1:]


          V1     V2        V3      V4      V5      V6       V7      V8  \
0       63.8  215.6   57.6000    0.00    0.00    0.00    0.000    0.00   
1        0.0    0.0    0.0000   52.00   77.00    0.00    0.000    0.00   
2       63.8  215.6   57.6000    0.00    0.00    0.00    0.000    0.00   
3        0.0    0.0    0.0000    0.00    0.00    0.00  -12.600   -7.80   
4        0.0    0.0    0.0000    0.00    0.00    0.00  -12.600   -7.80   
5        0.0    0.0    0.0000    0.00    0.00    0.00  -12.600   -7.80   
6       63.8  215.6   57.6000    0.00    0.00    0.00    0.000    0.00   
7       63.8  215.6   57.6000    0.00    0.00    0.00    0.000    0.00   
8        0.0    0.0    0.0000    0.00    0.00    0.00    0.000    0.00   
9       63.8  215.6   57.6000    0.00    0.00    0.00    0.000    0.00   
10       0.0    0.0   -2.0000   -7.00    8.90  153.80  152.900  152.90   
11      63.8  215.6   57.6000    0.00    0.00    0.00    0.000    0.00   
12       0.0    0.0    0.0000  -12.90 

In [39]:
def get_rf_acc(train_x, train_y, test_x, depth, trees):
    rf = RandomForestClassifier(max_depth=depth, n_estimators=trees)
    rf.fit(train_x, train_y)
    # test
    test_result = rf.predict(test_x)
    #cm = confusion_matrix (test_y, test_result)
    #acc = accuracy_score(test_y, test_result)
    return(test_result)

In [49]:
Untouched_104 = get_rf_acc(train_x,train_y,test, 4, 10)
Untouched_1016 = get_rf_acc(train_x,train_y,test, 16, 10)
Untouched_304 = get_rf_acc(train_x,train_y,test, 4, 30)
Untouched_3016 = get_rf_acc(train_x,train_y,test, 16, 30)
print(Untouched_104)
print(Untouched_1016)
print(Untouched_304)
print(Untouched_3016)

<class 'numpy.ndarray'>
[9 3 1 ... 4 9 6]
[9 3 2 ... 8 4 5]
[9 3 1 ... 6 9 0]
[9 3 2 ... 8 4 5]


In [56]:
touched_104 = get_rf_acc(new_train_x,train_y,new_test_x, 4, 10)
touched_1016 = get_rf_acc(new_train_x,train_y,new_test_x, 16, 10)
touched_304 = get_rf_acc(new_train_x,train_y,new_test_x, 4, 30)
touched_3016 = get_rf_acc(new_train_x,train_y,new_test_x, 16, 30)
print(touched_104)
print(touched_1016)
print(touched_304)
print(touched_3016)

[6 9 3 ... 8 4 6]
[6 9 3 ... 8 4 5]
[6 9 3 ... 6 9 6]
[6 9 3 ... 8 4 5]


In [58]:
df = pd.DataFrame(touched_1016)
df.to_csv("touched_1016.csv")